Config/queue.php, Console/Command/CronShell.php, Console/Command/QueueShell.php, README.md, Test/Case/Console/Command/QueueShellTest.php
Hello,
I am making this pull request to propose adding a few minor tweaks I made to a few areas of this plugin that I think will improve its quality.  The changes are as follows:
1.  Renamed the configuration variable `gcprop` to `gcprob` in the entire plugin.
I assume that `gcprop` stands for "garbage collection propability".  Unfortunately "propability" is a typo, the actual world is "probability" so some people may find the name of the configuration option confusing.
2.  Fixed the "propability" typo in the README (it is now "probability").
Self explanatory.
3.  Added a few lines about how to use `createJob()` to the README.
When I first read the README, I was not exactly sure how to use `createJob()`.  I had to look at the example files and try it out myself to understand what the two …
=> Typo fix, README additions, Config/queue.php comments

Config/Schema/queue.php, Config/Schema/schema.php, Model/QueuedTask.php
There is an updateProgress() model method but the field wasn’t included in the schema.
I’m guessing it should also include the field in the _findProgress() method.
This could be a precursor to introducing a progress bar for the console output.
=> Add progress field

Console/Command/Task/QueueEmailTask.php, Console/Command/Task/QueueExampleTask.php, Console/Command/Task/QueueExecuteTask.php, Console/Command/Task/QueueLongExampleTask.php, Console/Command/Task/QueueRetryExampleTask.php, Console/Command/Task/QueueSuperExampleTask.php
QueueShell::runworker() passes the id of the QueuedTask when it calls
the run method on the task. The QueueLongExampleTask included the
argument but the rest were missing.
=> Add $id to arguments of run method in example tasks

config/Migrations/20150425180802_init.php, config/Migrations/20150511062806_fixmissing.php
While trying to execute migration of this plugin I noticed these errors.
In initial migration, down() method was empty, so we can't rollback the migration.
In second migration, update() should be called instead of create().
=> Fix migration errors

src/Shell/Task/QueueSuperExampleTask.php
To obtain the fatal error try:
```cake queue add SuperExample```
```cake queue runworker```
=> class not found fix

src/Model/Table/QueuedTasksTable.php
This fixes updating of the failed count in the queued_tasks table in my case. I'm running CakePHP 3 and MySQL.
=> Fix failed increment

config/Migrations/20150911132343_improvements_for_mysql.php
Hi! Was having issues with this version of mysql
```
$ mysql --version
mysql  Ver 14.14 Distrib 5.6.24, for debian-linux-gnu (x86_64) using  EditLine wrapper
```
This is fixed by this.
It wouldn't even touch the table, because no default value was set for the column `status` - I just figured I could as well fix the other ones... :smile:
=> Improvements for it to be working on MySQL that is not MariaDB fork

src/Model/Table/QueuedTasksTable.php, tests/TestCase/Model/Table/QueuedTasksTableTest.php
I have fixed the unit tests in the 3.x branch so I get all passes.  In addition to the intermittent rate-limiting issues you mentioned in #71 I was also encountering other failures that I believe stemmed from timestamp inconsistencies, which I was able to fix by using CakePHP's Time() class.
=> Fix unit tests

src/Mailer/Transport/SimpleQueueTransport.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php
SimpleQueueTranport extracts config from email to save space in db (for example with mails with attachments) and recreates them in email task
=> add new transport

config/Migrations/20161319000000_increase_data_size.php
For LONGTEXT support. fixes #76 
Data field maximum size is increased from 64KiB to 4GiB
=> Increase data field size

src/Model/Table/QueuedTasksTable.php
I came across a situation where the created & fetched times were a timezone offset's distance apart from the completed time.  Using date('Y-m-d H:i:s') instead of time() matches completed time up with how created and fetched are set. (And fixed the offset issue)
=> Set completed time in the same way other timestamps are set.

src/Shell/QueueShell.php
This is to avoid notice when ``$pidFilePath`` is not empy but ``$pidFilePath . 'queue_' . $pid . '.pid'`` does not exist.
=> Fix unlink warn when pid file does not exist

src/Mailer/Transport/SimpleQueueTransport.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php
when some of the values are null when recreating email it throws invalid argument exception so to bypass it just unset email settings that are empty
=> add checks to empty values

Model/QueuedTask.php
Tiny tweak for the 2.x branch: the query in QueuedTasks->getTypes() does a "list" find with a single "fields" parameter and a single "group" parameter.
Cake automatically adds the primary key to the "fields" array, and the resulting query breaks MySql if it's configured with strict GROUP BY rules:
```sql
SELECT QueuedTask.id, QueuedTask.jobtype
FROM queued_tasks QueuedTask
GROUP BY QueuedTask.jobtype
```
```
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'QueuedTask.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by
```
Adding a second copy of "jobtype" to the "fields" parameter fixes the issue, and Cake is smart enough …
=> Fix query when MySql configured with sql_mode=only_full_group_by

src/Mailer/Transport/SimpleQueueTransport.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php
Email->subject() returns encoded text, we want to get decoded text instead
=> fix subject with UTF chars for simpleQueueTransport

Config/Migration/1453822680_adding_priority_field_to_queue_tasks.php, Console/Command/QueueShell.php, Model/CronTask.php, Model/QueuedTask.php
This includes our changes to the Queue plugin.  There are two main changes included with this pull request.
1. We added the concept of priority to queued tasks.  By default all tasks will have a priority of 5.  But you can specify a lower number like 3 and this will place the task in front of those with 5.
`$this->QueuedTask->nextPriority(2)->createJob('YourSuperCoolTask', [
'some_id' => '12345',
]);`
1. We have had cases where a task that is working with a remote api fails because of exceptions raised when the API is down.  We should be catching these exceptions in the task and handle failure there.  But this is a fail safe.  We added a try catch block that will log any exception making it up to the runworker method. then mark the task as failed and move on with out causing the worker to …
=> Symphosize improvements

.gitignore, Console/Command/CronShell.php, Console/Command/QueueShell.php, Model/CronTask.php, Model/QueuedTask.php, README.md, Test/Case/Model/QueuedTaskTest.php, Test/Case/Network/Email/QueueTransportTest.php
We've had recurring problems with data becoming corrupt and/or damaged. Initially we assumed it was the TEXT limit being hit, but what's actually a cause is that the data isn't being stored correctly.
php's serialize methods don't sanitize their data. So if you have for example html with double quotes, that'll break your serialized array. 
Initially the thought was to essentially run through the data to be serialized and addslashes. However this had it's own issues if you start going down into recursive arrays.
A simpler fix was to simply switch out to json_encode / json_decode as this is able to both retain data integrity, and doesn't suffer from the same sanitization issue as serialize.
=> 2.x switch to json

src/Shell/QueueShell.php
```
$ bin/cake Migrations.migrate -p Queue
Exception: Shell class for "Migrations.Migrate" could not be found. in [/var/www/cakephp/app/vendor/cakephp/cakephp/src/Console/ShellDispatcher.php, line 327]
```
The dot won't work for me (anymore, used to in 2.x AFAIR).
=> Report correct command via queue install

config/Migrations/20171013133145_Utf8mb4Fix.php
Fixes https://github.com/dereuromark/cakephp-queue/issues/147
=> Set utf8mb4 / bin as safe default for char/text fields aside pid

src/Model/Table/QueuedJobsTable.php
If posix is not enabled the filename is created as sha1 hash:
```php
Queue\Shell\QueueShell
/**
* @return string
*/
protected function _retrievePid() {
if (function_exists('posix_getpid')) {
$pid = (string)posix_getpid();
} else {
$pid = $this->QueuedJobs->key();
}
return $pid;
}
```
and `$pid = $this->QueuedJobs->key();` is set as
```php
/**
* Generates a unique Identifier for the current worker thread.
*
* Useful to identify the currently running processes for this thread.
*
* @return string Identifier
*/
public function key() {
if ($this->_key !== null) {
return $this->_key;
}
$this->_key = sha1(microtime());
return $this->_key;
}
```
=> fix if posix is not enabled (e.g. Windows)

src/Shell/Task/QueueEmailTask.php
PR to fix issue #169 
By default the `transport` property of the non-queue transport email config was not used, but the first one (default) 
This is fixed by using the `transport` property of the available `$data` containing the config of the email transport
=> Fix to follow email transport defined in app.php

src/Controller/Admin/QueueController.php
Warning (512): Method Cake\View\Helper\TimeHelper::relLengthOfTime does not exist [CORE\src\View\Helper.php, line 139]
=> Fixing warning on backoffice when runworker is running

src/Shell/QueueShell.php
We should just default the input to `all` so the command can be run non-interactive.
Fixes #199
=> Defaults the kill input to 'all' so it can be run non-interactive

src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php
Do not typecast PID to int in `bin/cake queue end` as PID can be integer or sha1.
Ending workers failed because `58dfbdc23c1a8...` was typecasted to `58` and didn't match any process.
Also I'm reverting my previous PR #209 as some systems use hardcoded process IDs (#210).
=>  Do not typecast PID to int

composer.json, docs/CONTRIBUTING.md, docs/README.md, src/Controller/Admin/QueuedJobsController.php, src/Locale/queue.pot, src/Shell/QueueShell.php, src/Shell/Task/QueueExampleTask.php, src/Shell/Task/QueueExceptionExampleTask.php, src/Shell/Task/QueueExecuteTask.php, src/Shell/Task/QueueRetryExampleTask.php, src/Shell/Task/QueueSuperExampleTask.php, src/Template/Admin/Queue/index.ctp, src/Template/Admin/Queue/processes.ctp, src/Template/Admin/QueueProcesses/edit.ctp, src/Template/Admin/QueueProcesses/index.ctp, src/Template/Admin/QueueProcesses/view.ctp, src/Template/Admin/QueuedJobs/data.ctp, src/Template/Admin/QueuedJobs/edit.ctp, src/Template/Admin/QueuedJobs/execute.ctp, src/Template/Admin/QueuedJobs/import.ctp, src/Template/Admin/QueuedJobs/index.ctp, src/Template/Admin/QueuedJobs/test.ctp, src/Template/Admin/QueuedJobs/view.ctp, src/View/Helper/QueueProgressHelper.php, tests/TestCase/View/Helper/QueueProgressHelperTest.php
Using Tools plugin 1.9.6+ you can also use the more visual progress bar (or any custom one of yours):
```php
echo $this->QueueProgress->progressBar($queuedJob, 18);
```
The length refers to the amount of chars to display.
Make sure you loaded the helper in your AppView class.
By default it first tries to use the actual `progress` stored as value 0...1.
If that field is `null`, it tries to use the statistics of previously finished jobs of the same task
to determine average length and displays the progress based on this.
=> Add progress info and bars.

config/Migrations/20161319000000_increase_data_size.php, config/Migrations/20171013131845_AlterQueuedJobs.php, config/Migrations/20171013133145_Utf8mb4Fix.php
I'm using Postgres 11 and the migrations below failed on a freshly installed migration. Code now uses existing try catch (which appeared ineffective in my case) as well as a test instance of condition.
Hopefully this makes sense and incorporation in the code base will make it better for Postgres users.
=> Only do MySQL specific migrations for MySQL

src/Model/Table/QueuedJobsTable.php
This PR fix runworker error for Postgresql
Job Finished.
---------------------------------------------------------------
[2019-09-08 23:43:12] Looking for Job ...
Exception: SQLSTATE[42883]: Undefined function: 7 ERROR:  function unix_timestamp() does not exist
LINE 1: ...d < $3 OR (fetched) IS NULL)) AND failed < $4 AND UNIX_TIMES...
^
=> Fix: Postgres error on runworker

src/Model/Table/QueuedJobsTable.php
This is a fix for #228.
For some reason, when running from a CGI such as php-fpm, PCNTL signals constants are not defined and `posix_kill()` fails to send the signal. Yet the constants are defined when running from CLI, which is very confusing.
This is exactly the behavior Martin mentioned [here](https://www.php.net/manual/fr/function.posix-kill.php#117225).
=> Fix sending signal from CGI

docs/README.md, src/Queue/Task/EmailTask.php
Closes #282 
This adds support for reusable emails for the Email task.
Basically I introduced 2 new keys in the $data array: `action` and `actionVars`.
If both are present they will be used to send the desired reusable email.
Otherwise if either one of those keys is not present the default `->deliver($content)` logic persists.
=> Add Reusable emails support for Email task

docs/README.md
I had to look up the sort direction how the worker gets the next task from the queue.
For some reason I thought a higher priority number means it is executed earlier, which is not the case.
=> Doc: Added clarification about priority order

composer.json, config/routes.php
Fixes #303
I am not able to run all tests locally because I am not on Linux (and your tests require linux)
But this actually fixes the deprecation warning in CakePHP 4.3 but should still be backwards compatible.
=> fix CakePHP 4.3 deprecation warnings in routes.php

src/Controller/Admin/LoadHelperTrait.php
On pages like the QueuedJobs overview there is a new deprecation warning.
Unfortunately this message first leads to a core issue but it actually is related to this plugin.
As seen in the code changed the config for the Tools Helper is not set correctly.
Therefore the Tools.Time Helper is loaded with its default config which is currently the deprecated Time Helper.
Therefore this warning is being shown.
Don't know if we need to adjust the array for older CakePHP versions but I hope the tests will show some more info 😄
=> fix LoadHelperTrait not setting config correctly

templates/Admin/Queue/index.php
The [default config file](https://github.com/dereuromark/cakephp-queue/blob/master/config/app_queue.php) contains the settings `plugins` and `ignoredTasks` which are arrays. 
The rendering of the edited template fails because arrays must not be passed to `is_dir()`.
=> Don't pass arrays to is_dir()

src/Model/Table/QueuedJobsTable.php
Error traceback:
`2022-03-21 18:00:07 Error: [PDOException] SQLSTATE[42000]: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The datediff function requires 3 argument(s). in D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php on line 178
Stack Trace:
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php:178
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Connection.php:337
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Core\Retry\CommandRetry.php:70
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Connection.php:340
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\Database\Query.php:250
- D:\home\site\wwwroot\vendor\cakephp\cakephp\src\ORM\Query.php:1148
- …
=> Fixing Error on SQLSERVER related to Datediff

.github/workflows/ci.yml, composer.json, phpstan.neon, src/Command/InfoCommand.php, src/Controller/Admin/QueueController.php, src/Controller/Admin/QueueProcessesController.php, src/Controller/Admin/QueuedJobsController.php, src/Migration/OldTaskFinder.php, src/Model/Table/QueueProcessesTable.php, src/Model/Table/QueuedJobsTable.php, src/Queue/Processor.php, src/Queue/Task.php, src/Queue/Task/ExecuteTask.php, src/Queue/TaskFinder.php, src/View/Helper/QueueProgressHelper.php
Fixes #325
BUT there is still a problem which I can't really get my head around.
Its about the new `->fetchTable()` method from the `LocatorAwareTrait` not returning the "correct" types even though https://github.com/CakeDC/cakephp-phpstan is installed.
I was able to easily replace the deprecated `Cake\Filesystem\Folder` class usages with just some plain old `glob()` functions. No need for SPL classes.
The changes in the `composer.json` are just my editor re-ordering the packages alphabatically. If this is a problem I can for sure just return that to its original state (and I declared to use phpstan 1.5 and requiring PHP 7.4)
=> fix deprecations

composer.json, src/Model/ProcessEndingException.php
Seems like PHPStan doesn't understand the alias we are setting via
```
class_alias('Cake\Core\Exception\CakeException', 'Cake\Core\Exception\Exception');
```
So I used the new exception class now.
=> fix exception error on phpstan

src/Model/Table/QueuedJobsTable.php
Sometimes we get random SQL errors like this one when running the queue worker:
```
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '35a454c17942a60acb27fb20fccb3cce8e1b70b0' for key 'workerkey'
```
seems like under certain (unknown) circumstances the generated workerkey name is not unique because `microtime()` seems to return the same value for different workers.
This fix should at least reduce the chance of generating exactly the same workerkey.
=> add random number to workerkey generation

Model/QueuedTask.php
I've spent the last day troubleshooting an odd issue with the CakePHP 2.x version of this library. I eventually tracked it down to the following query returning records that were updated in the previous run:
```
// Read which one actually got updated, which is the job we are supposed to execute.
$data = $this->find('first', [
'conditions' => [
'workerkey' => $key,
'completed' => null,
],
'order' => ['fetched' => 'DESC']
]);
```
Disabling queryCache for the worker resolves this issue. I realise it's an old version but thought I'd offer the PR anyway.
Thanks,
Ben
=> CakePHP 2.x - Don't cache queries for QueuedTasks

composer.json, config/app.example.php, src/Command/InfoCommand.php, src/Command/JobCommand.php, src/Command/WorkerCommand.php, src/Controller/Admin/QueueProcessesController.php, src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueuedJobsTable.php, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/TestCase/Queue/Task/EmailTaskTest.php, tests/TestCase/Queue/TaskFinderTest.php, tests/TestCase/View/Helper/QueueProgressHelperTest.php, tests/bootstrap.php
I am not quite sure what the current state of the MailerTask is in this cake5 branch.
These tests fail because `$data['settings']` can either be a Mailer instance or a Message object so
```
$data['settings'] + $this->defaults
```
is not really valid.
Whats your suggestion?
=> cake5 upgrade

src/Controller/Admin/QueuedJobsController.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php, tests/TestCase/Queue/ProcessorTest.php
There were 2 failing tests, one is fixed, one is removed because it referenced a deprecated trait
=> Fixing tests for cake5 upgrade

config/Migrations/20230102000001_MigrationQueueReplaceFailedWithAttempted.php, docs/sections/queueing_jobs.md, src/Command/JobCommand.php, src/Controller/Admin/QueueController.php, src/Controller/Admin/QueuedJobsController.php, src/Model/Entity/QueuedJob.php, src/Model/Table/QueuedJobsTable.php, src/Queue/Processor.php, src/View/Helper/QueueHelper.php, templates/Admin/Queue/index.php, templates/Admin/QueuedJobs/index.php, templates/Admin/QueuedJobs/view.php, tests/Fixture/QueuedJobsFixture.php, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/TestCase/View/Helper/QueueHelperTest.php, tests/test_files/queued-job.json
Change "failed" column to "attempts" and update logic accordingly (and increment this value prior to job execution).
If I have a job that causes the process to run out of memory, the job is never marked as failed, and later workers will pick it up and try to execute it again regardless of the "retries" task property. This can cause the queue_processes table to fill up when there are in fact no workers running, and prevents the start up of new workers.
There are a few ways around this but I feel like the above would be a simpler way to prevent this kind of problem from happening.
=> Change "failed" column to "attempts"

src/Queue/TaskFinder.php
Related to https://github.com/dereuromark/cakephp-queue/issues/379
=> Fixed TaskFinder failing to find tasks if app directory is not 'src'

composer.json, docs/sections/upgrading.md, phpunit.xml.dist, src/Controller/Admin/QueueController.php, src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueuedJobsTable.php, src/Queue/Task/ProgressExampleTask.php, tests/TestCase/Controller/Admin/QueueProcessesControllerTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/bootstrap.php
I didn't want to remove the used constants like `MINUTE` or `DAY` so I added those to the classes where they were (solely) used.
=> 5.x: phpunit 10 upgrade

src/Model/Table/QueueProcessesTable.php, src/Model/Table/QueuedJobsTable.php, src/Queue/Config.php
See #400 for explanation. 
- Fixes error in not using a relative DateTime for finding running jobs which are out of time
- Throw exception for usage of defaultworkertimeout of 0 seconds as it is clearly not supported.
=> Improve usage of defaultworkertimeout

composer.json, src/Model/Table/QueuedJobsTable.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/test_app/src/Dto/MyTaskDto.php
As discussed in https://github.com/dereuromark/cakephp-queue/issues/410 this is all we can do for now it seems.
It is optional, so everything works also as before
The idea is to have a bit more native DTO support built in
Now you can do
`bin/cake dto generate` for
```xml
<dto name="EventUpdateNotificationQueueData" immutable="true">
<field name="eventId" type="int" required="true"/>
<field name="mailer" type="string" required="true"/>
<field name="type" type="string" required="true"/>
</dto>
```    
and
```php
$dataDto = OrderUpdateNotificationQueueDataDto::createFromArray([
OrderUpdateNotificationQueueDataDto::FIELD_ORDER_ID => $order->id,
OrderUpdateNotificationQueueDataDto::FIELD_MAILER => 'Request',
OrderUpdateNotificationQueueDataDto::FIELD_TYPE => 'requestToEventsetting',
]); …
```
=> Support DTO like input.

src/Queue/ServicesTrait.php
Related Issue: https://github.com/dereuromark/cakephp-queue/issues/414
=> add generic type hint + helpful exception for ServicesTrait
