dereuromark/cakephp-queue

README.md
I think this should be mentioned in the doc. See #20.
=> Mention cleanuptimeout configuration parameter

Controller/QueueController.php
=> Add helpers for admin_index page

Model/QueuedTask.php
So it can be used in more places.
=> Move status to virtualField

Controller/QueueController.php, Model/QueuedTask.php, View/Queue/admin_index.ctp
I added some more detailed information for tasks which are not yet completed and fixed the reset method.
=> Updates and bug fixes to admin_index page

Console/Command/Task/QueueExampleTask.php, Console/Command/Task/QueueExecuteTask.php, Console/Command/Task/QueueLongExampleTask.php, Console/Command/Task/QueueRetryExampleTask.php, Console/Command/Task/QueueSuperExampleTask.php, Console/Command/Task/QueueTask.php, README.md
To make it easier to develop custom tasks I've added a QueueTask class to extend that contains the basic properties and methods required for a queue task. The examples and readme have been updated accordingly.
I feel this makes it a little easier to start developing custom tasks as a beginner as it makes it simpler to see what is needed in order to write one.
=> Added QueueTask class.

config/Migrations/20150425180802_init.php, config/Migrations/20150511062806_fixmissing.php, config/Schema/queued_tasks.php, src/Model/Table/QueuedTasksTable.php, src/Shell/Task/QueueEmailTask.php, src/Shell/Task/QueueLongExampleTask.php, tests/Fixture/QueuedTasksFixture.php, tests/TestApp/Model/Table/QueuedTasksTable.php, tests/TestCase/Model/Table/QueuedTasksTableTest.php, tests/TestCase/Network/Email/QueueTransportTest.php, tests/TestCase/Shell/QueueShellTest.php
Some migrations to CakePHP 3.x
=> Upgrade3xy

src/Shell/QueueShell.php
Path was in the old CakePHP 2 format.
=> Fixed path to app tasks.

README.md
=> updated notes in documentation

config/Migrations/20150425180802_init.php
=> Fixed initial migration to support Postgres and other db adapters

config/Migrations/20150911132343_improvements_for_mysql.php
Damn - I wasn't completely awake when doing #59 - this is the corrected version....
I'm terribly sorry - the changes in #59 doesn't break anything, it's just not necessary.
=> Removed everything else beside status

Console/Command/CronShell.php
=> fixed spelling mistake

README.md
The verb "wants" does not need an apostrophe
=> remove Bad Apostrophe

src/Shell/Task/QueueEmailTask.php
as a separate pr as we discussed.
=> Call to undefined method Cake\Mailer\Email::transportClass() issue fix 

src/Model/Table/QueuedTasksTable.php
see #95 
ended up rewriting requestJob,
please double check :)
=> rewrite requestJob a bit

src/Model/Table/QueuedJobsTable.php
Little fix for completed datetime
=> Fix completed datetime bug

docs/README.md
Something I found while I am using this package.
=> fixed doco

docs/README.md
=> replace status with progress in Updating Progress

docs/README.md
removed `:dev-master` from installation doc. 
composer will install latest release itself
=> remove dev-master

src/Controller/Admin/QueueController.php, src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php, src/Template/Admin/Queue/index.ctp, src/Template/Admin/Queue/processes.ctp
Might fix https://github.com/dereuromark/cakephp-queue/issues/121
@tyalcinkaya @mattvision please confirm
=> Fix duplicates on job processing

config/app_queue.php
=> Remove 2.x relic Queue.notify

config/Migrations/20171013131845_AlterQueuedJobs.php
=> Alter Table Column failure_message field from type text to mediumtext via migration

config/Migrations/20171019083500_fix_cloumn_length.php, src/Model/Table/QueuedJobsTable.php, tests/Fixture/QueueProcessesFixture.php
can be extended for other RDMBS. Local Tests on SQL Server are passing. Hopefuly for MySQL will still pass, too 😄
=>  first implementation of SQL Server Support

config/Migrations/20171013133145_Utf8mb4Fix.php
instead of https://github.com/dereuromark/cakephp-queue/commit/dbe5834786fe011aa2bb1090b42e5ccd69b99eb4
=> Fix migration strings

src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php, tests/TestCase/Mailer/Transport/QueueTransportTest.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
Closes https://github.com/dereuromark/cakephp-queue/issues/151
=> fix #151: use serialize instead of json_encode

src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueueProcessesTable.php, src/Model/Table/QueuedJobsTable.php, src/Template/Admin/Queue/index.ctp, src/Template/Admin/QueuedJobs/edit.ctp, src/Template/Admin/QueuedJobs/index.ctp, src/Template/Admin/QueuedJobs/view.ctp, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php, tests/bootstrap.php
Raising prio of some pending tasks is now possible.
=> Add jobs edit of prio.

src/Controller/Admin/QueueController.php, src/Model/Table/QueueProcessesTable.php
=> Fixing date in QueueController and QueueProcessesTable

src/Mailer/Transport/QueueTransport.php, src/Mailer/Transport/SimpleQueueTransport.php, src/Model/Table/QueuedJobsTable.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php
replaces https://github.com/dereuromark/cakephp-queue/pull/181
=> 3.6 compatibility

docs/README.md
Resolves https://github.com/dereuromark/cakephp-queue/issues/174
=> status docs.

config/app_queue.php, docs/README.md, src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueuedJobsTable.php, src/Shell/Task/QueueProgressExampleTask.php, src/Template/Admin/Queue/index.ctp, src/Template/Admin/QueuedJobs/stats.ctp, src/Template/Admin/QueuedJobs/test.ctp
Also improved updateProgress() to allow status update.
=> Delay fixes using FrozenTime and stats.

config/app_queue.php, config/bootstrap.php, src/Controller/Admin/QueueController.php, src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueueProcessesTable.php, src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php, tests/TestCase/Mailer/Transport/QueueTransportTest.php, tests/TestCase/Mailer/Transport/SimpleQueueTransportTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
Implements https://github.com/dereuromark/cakephp-queue/pull/141
also fixes some datetime timezone issues.
=> Use getOrFail() for important config.

src/Model/Table/QueuedJobsTable.php
PR for [issue 106](https://github.com/dereuromark/cakephp-queue/issues/106)
Sorry PR without tests.
=> Fix runworker with postgres database.

composer.json, src/Controller/Admin/QueuedJobsController.php, src/Model/Table/QueuedJobsTable.php, src/Template/Admin/QueuedJobs/index.ctp
=> Removing deprecated warning

config/Migrations/20171019083502_MigrationQueueStatus.php, docs/README.md, src/Model/Entity/QueueProcess.php, src/Model/ProcessEndingException.php, src/Model/Table/QueueProcessesTable.php, src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php, tests/TestCase/Model/Table/QueueProcessesTableTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
Partially resolves the https://github.com/dereuromark/cakephp-queue/issues/201 issues
=> Better deploy window handling.

.travis.yml
Use https://github.com/dereuromark/composer-prefer-lowest
=> validate prefer lowest.

docs/README.md, src/Shell/QueueShell.php, src/Shell/Task/QueueEmailTask.php, src/Shell/Task/QueueExampleTask.php, src/Shell/Task/QueueProgressExampleTask.php, src/Shell/Task/QueueRetryExampleTask.php, src/Shell/Task/QueueSuperExampleTask.php
Some of https://github.com/dereuromark/cakephp-queue/pull/159 can actually go into master already.
=> Pull some 4.x changes into master.

docs/README.md
Not really significant, just for practicality
=> Updated for after cakephp 3.6

tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/TestCase/Shell/QueueShellTest.php, tests/TestCase/View/Helper/QueueProgressHelperTest.php
Enable tests for postgres
Refs https://github.com/dereuromark/cakephp-queue/pull/241
=> Run tests also for Postgres.

config/app_queue.php, src/Model/Table/QueuedJobsTable.php, src/Shell/QueueShell.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
This is a backport of #228, #272 and #273 to the cake3 branch.
=> Backport workers wake up feature to cake3

src/Model/Table/QueuedJobsTable.php, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Controller/Admin/QueuedJobsControllerTest.php
Implements https://github.com/dereuromark/cakephp-queue/issues/268
=> SQlite fix

src/Model/Entity/QueueProcess.php, src/Model/Table/QueueProcessesTable.php, templates/Admin/Queue/processes.php
Closes #281 
This adds the currently active job to the process view.
=> Add currently active job to worker processes view

src/Model/Table/QueueProcessesTable.php
well, I am not used to CS checking before commiting/pushing 😅
=> fix CS error introduced by last PR

tests/TestCase/Model/Table/QueuedJobsTableTest.php
I admit that I'm somewhat new at these test cases via Github PR, so go easy me if this is complete garbage.
=> my attempt at a test case for "skipExistenceCheck" set to true

config/app_queue.php, docs/README.md, src/Model/Table/QueuedJobsTable.php, src/Queue/Config.php, src/Queue/Processor.php, src/Queue/Task.php, src/Queue/TaskFinder.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
Resolves https://github.com/dereuromark/cakephp-queue/issues/288
=> Allow skipping check of existence.

docs/README.md
Just noticed that the doc is not up2date 😉
=> Update QueueTask bake generation doc

src/Queue/Task/EmailTask.php, tests/TestCase/Queue/Task/EmailTaskTest.php
QueueTransport puts Message object into Job, but EmailTask expected Mailer object or array, not Message object. Added handling of Message objects to EmailTask and added a Test Case to cover the new usage.
Resolves https://github.com/dereuromark/cakephp-queue/issues/314
=> EmailTask handling Cake\Mailer\Message

docs/README.md, src/Command/RunCommand.php
In default and verbose mode it should log for sure.
=> Fix logging for all cases except quiet mode

config/app_queue.php, docs/README.md, src/Queue/Config.php, src/Queue/TaskFinder.php
=> Makes possibile to ignore tasks

docs/README.md
=> added documentation for DI container usage in tasks

src/View/Helper/QueueHelper.php
Found another small deprecation.
Don't know why this Trait was in there in the first place to be honest...
=> fix deprecation

src/Controller/Admin/QueueController.php, src/Queue/AddFromBackendInterface.php, src/Queue/Task/CostsExampleTask.php, src/Queue/Task/EmailTask.php, src/Queue/Task/ExampleTask.php, src/Queue/Task/ExceptionExampleTask.php, src/Queue/Task/MonitorExampleTask.php, src/Queue/Task/ProgressExampleTask.php, src/Queue/Task/RetryExampleTask.php, src/Queue/Task/SuperExampleTask.php, src/Queue/Task/UniqueExampleTask.php, src/Queue/TaskFinder.php, templates/Admin/Queue/index.php, tests/test_files/bake/task.php
This will not show tasks that cannot be added via backend as they need arguments to run
=> Allow adding only CLI vs WEB.

docs/README.md
=> Console info added

config/app_queue.php, docs/README.md, src/Command/JobCommand.php, src/Model/Table/QueuedJobsTable.php, src/Queue/Processor.php, src/Utility/JsonSerializer.php, src/Utility/ObjectSerializer.php, src/Utility/Serializer.php, src/Utility/SerializerInterface.php, templates/Admin/QueuedJobs/view.php, tests/TestCase/Utility/JsonSerializerTest.php, tests/TestCase/Utility/ObjectSerializerTest.php
Resolves https://github.com/dereuromark/cakephp-queue/issues/155
Refs https://github.com/dereuromark/cakephp-queue/pull/153
```php
'Queue' => [
...
'serializerClass' => \Queue\Utility\JsonSerializer::class,
'serializerConfig' => [...],
],
```
=> Allow configuration of Serializer

phpstan.neon, src/Queue/Task/EmailTask.php, src/Queue/Task/ExecuteTask.php, src/Queue/Task/MailerTask.php, tests/TestCase/Queue/Task/EmailTaskTest.php
Follow https://github.com/dereuromark/cakephp-queue/pull/355 for Message usage directly via JSON serializer
=> Allow Email via Message settings instead of object.

src/Model/Table/QueuedJobsTable.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php
Resolves https://github.com/dereuromark/cakephp-queue/issues/356
=> Fix up SQLite

docs/CONTRIBUTING.md, tests/bootstrap.php
I believe these need to be updated
=> Improving contributing doc and fixing db connection in test bootstrap

docs/CONTRIBUTING.md, docs/sections/custom_tasks.md, src/Command/BakeQueueTaskCommand.php, src/Queue/TaskFinder.php, templates/bake/Task/task.twig, tests/TestCase/Command/AddCommandTest.php, tests/TestCase/Command/BakeQueueTaskCommandTest.php, tests/TestCase/Command/InfoCommandTest.php, tests/TestCase/Queue/TaskFinderTest.php, tests/test_app/plugins/Foo/src/Queue/Task/Sub/SubFooTask.php, tests/test_app/src/Queue/Task/Sub/SubFooTask.php, tests/test_files/bake/Sub/task.php, tests/test_files/bake/Sub/task_test.php, tests/test_files/bake/task.php
Resolves https://github.com/dereuromark/cakephp-queue/issues/371
Requires
Any help welcome
=> Organize tasks in subfolders.

.gitignore, docs/CONTRIBUTING.md, docs/sections/custom_tasks.md, src/Command/BakeQueueTaskCommand.php, src/Queue/TaskFinder.php, tests/TestCase/Command/BakeQueueTaskCommandTest.php, tests/TestCase/Command/InfoCommandTest.php, tests/TestCase/Queue/TaskFinderTest.php, tests/test_app/plugins/Foo/src/Queue/Task/Sub/SubFooTask.php, tests/test_app/src/Queue/Task/Sub/SubFooTask.php, tests/test_files/bake/Sub/task.php, tests/test_files/bake/Sub/task_test.php, tests/test_files/bake/task.php
Or do you rather prefer a rebase?
=> merge master => cake5

README.md, composer.json, phpunit.xml.dist, src/Command/InfoCommand.php, src/Command/JobCommand.php, src/Command/WorkerCommand.php, src/Controller/Admin/QueueController.php, src/Controller/Admin/QueueProcessesController.php, src/Controller/Admin/QueuedJobsController.php, tests/TestCase/Command/AddCommandTest.php, tests/TestCase/Command/BakeQueueTaskCommandTest.php, tests/TestCase/Command/InfoCommandTest.php, tests/TestCase/Command/JobCommandTest.php, tests/TestCase/Command/MigrateTasksCommandTest.php, tests/TestCase/Command/RunCommandTest.php, tests/TestCase/Command/WorkerCommandTest.php, tests/TestCase/Controller/Admin/QueueControllerTest.php, tests/TestCase/Model/Table/QueuedJobsTableTest.php, tests/TestCase/View/Helper/QueueProgressHelperTest.php
Some are not fixable right now it seems
=> Remove deprecations

config/Migrations/202311128071500_MigrationAddIndex.php
=> add index to queued_jobs table

config/Migrations/20231112807150_MigrationAddIndex.php
Resolves https://github.com/dereuromark/cakephp-queue/issues/407
=> Make sure this works for mssql.

composer.json, config/app.example.php, src/Controller/Admin/LoadHelperTrait.php, templates/Admin/Queue/index.php, templates/Admin/QueueProcesses/index.php, templates/Admin/QueueProcesses/view.php, templates/element/yes_no.php, tests/bootstrap.php, tests/test_app/src/View/AppView.php
For new v8
graceful fallback to status quo
=> Use new templating plugin where possible.

src/Model/Table/QueueProcessesTable.php
I hope I did everything correctly.
=> FIX: issue #431
